from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re

from .config import ProjectConfig, resolve_symbolic_path
from .evidence import ensure_registry
from .graph import build_graph, validate_graph
from .traceability import traceability_matrix_report


REPORT_PATH = "reports/repository-integrity-audit.md"


@dataclass(frozen=True)
class IntegrityFinding:
    finding_id: str
    severity: str
    area: str
    source: str
    impact: str
    required_action: str
    owner: str
    status: str = "Open"


REQUIRED_DOCS = [
    "discovery/product-discovery-spec.md",
    "discovery/research-plan.md",
    "discovery/assumptions.md",
    "canon/product-canon.md",
    "canon/vision.md",
    "canon/product-principles.md",
    "canon/non-negotiables.md",
    "strategy/icp.md",
    "strategy/buyer-user-model.md",
    "requirements/product-requirements.md",
    "requirements/acceptance-criteria.md",
    "domain/domain-overview.md",
    "domain/ubiquitous-language.md",
    "domain/bounded-contexts.md",
    "architecture/overview.md",
    "architecture/component-architecture.md",
    "roadmap/master-roadmap.md",
    "execution/phase-4-evolution.md",
    "validation/test-strategy.md",
    "validation/validation-report.md",
    "deployment/release-process.md",
    "deployment/production-checklist.md",
    "operations/runbook.md",
    "operations/learning-records.md",
    "governance/documentation-governance.md",
    "governance/architecture-governance.md",
    "governance/adr-process.md",
    "governance/traceability-model.md",
    "governance/quality-gates.md",
    "governance/repository-integrity-audit.md",
    "governance/contradictions.md",
]


def write_integrity_audit(repo_root: Path, cfg: ProjectConfig) -> tuple[Path, list[IntegrityFinding]]:
    root = resolve_symbolic_path("$WIKI_ROOT", cfg, repo_root)
    findings = integrity_findings(repo_root, cfg)
    report = integrity_report(findings)
    path = root / REPORT_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(report.rstrip() + "\n", encoding="utf-8")
    _append_log(root, f"Generated repository integrity audit [[{REPORT_PATH.removesuffix('.md')}]].")
    return path, findings


def integrity_findings(repo_root: Path, cfg: ProjectConfig) -> list[IntegrityFinding]:
    root = resolve_symbolic_path("$WIKI_ROOT", cfg, repo_root)
    findings: list[IntegrityFinding] = []

    findings.extend(_missing_docs(root))
    findings.extend(_stale_docs(root))
    findings.extend(_broken_traceability(repo_root, cfg))
    findings.extend(_missing_adrs(root))
    findings.extend(_missing_tests(root))
    findings.extend(_missing_evidence(repo_root, cfg, root))
    findings.extend(_methodology_violations(root))
    findings.extend(_open_contradictions(root))

    return [
        IntegrityFinding(f"AUD-{idx:03d}", f.severity, f.area, f.source, f.impact, f.required_action, f.owner, f.status)
        for idx, f in enumerate(findings, start=1)
    ]


def integrity_report(findings: list[IntegrityFinding]) -> str:
    counts = {severity: sum(1 for f in findings if f.severity == severity) for severity in ["critical", "major", "minor", "info"]}
    lines = [
        "---",
        "type: integrity-audit",
        "status: active",
        "stage: governance-integrity",
        "---",
        "# Repository Integrity Audit",
        "",
        "Generated by `python3 tools/echel.py integrity audit`.",
        "",
        "## Summary",
        "",
        f"- Critical: {counts['critical']}",
        f"- Major: {counts['major']}",
        f"- Minor: {counts['minor']}",
        f"- Info: {counts['info']}",
        f"- Total findings: {len(findings)}",
        "",
        "## Findings",
        "",
        "| ID | Severity | Area | Source | Impact | Required Action | Owner | Status |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    if findings:
        for f in findings:
            lines.append(
                f"| {f.finding_id} | {f.severity} | {f.area} | `{_escape(f.source)}` | {_escape(f.impact)} | {_escape(f.required_action)} | {_escape(f.owner)} | {f.status} |"
            )
    else:
        lines.append("| AUD-000 | info | Audit | `repository` | No integrity findings were detected. | Continue routine governance review. | Governance Auditor | Resolved |")
    lines.extend(
        [
            "",
            "## Coverage",
            "",
            "- Missing docs",
            "- Stale docs",
            "- Broken traceability",
            "- Missing ADRs",
            "- Missing tests",
            "- Missing evidence",
            "- Methodology violations",
            "- Contradictions",
        ]
    )
    return "\n".join(lines)


def _missing_docs(root: Path) -> list[IntegrityFinding]:
    findings = []
    for rel in REQUIRED_DOCS:
        if not (root / rel).exists():
            findings.append(
                _finding(
                    "critical",
                    "Missing docs",
                    f"wiki/{rel}",
                    "Required lifecycle memory is absent, so agents may infer context from incomplete sources.",
                    "Create the missing artifact or record an accepted governance exception.",
                    "Governance Auditor",
                )
            )
    return findings


def _stale_docs(root: Path) -> list[IntegrityFinding]:
    findings = []
    markers = ("stale:", "status: deprecated", "status: superseded", "template tbd", "\ntbd", "| tbd")
    for path in sorted(root.glob("**/*.md")):
        if "/reports/" in path.as_posix():
            continue
        text = path.read_text(encoding="utf-8", errors="ignore").lower()
        if any(marker in text for marker in markers):
            findings.append(
                _finding(
                    "major",
                    "Stale docs",
                    _rel(root, path),
                    "Artifact contains stale, deprecated, superseded, or TBD markers that may mislead downstream agents.",
                    "Resolve, replace, or explicitly accept the stale content.",
                    "Governance Auditor",
                )
            )
    return findings[:40]


def _broken_traceability(repo_root: Path, cfg: ProjectConfig) -> list[IntegrityFinding]:
    graph = build_graph(repo_root, cfg)
    findings = []
    for issue in validate_graph(graph):
        findings.append(
            _finding(
                issue.severity,
                "Broken traceability",
                "wiki/graph.json",
                issue.message,
                "Fix graph metadata, source links, or accepted exceptions.",
                "Governance Auditor",
            )
        )
    matrix = traceability_matrix_report(repo_root, cfg, graph=graph)
    for line in matrix.splitlines():
        match = re.match(r"- `([^`]+)` is missing (.+) links\.", line)
        if match:
            findings.append(
                _finding(
                    "major",
                    "Broken traceability",
                    "wiki/reports/traceability-matrix.md",
                    f"{match.group(1)} is missing {match.group(2)} links.",
                    "Add missing lifecycle links, evidence, or an explicit deferral.",
                    "Governance Auditor",
                )
            )
    return findings[:80]


def _missing_adrs(root: Path) -> list[IntegrityFinding]:
    findings = []
    adr_dir = root / "decisions"
    existing = {match.group(1) for path in adr_dir.glob("ADR-*.md") for match in [re.search(r"(ADR-\d{4})", path.name)] if match}
    referenced: set[str] = set()
    for path in sorted((root / "architecture").glob("*.md")) + sorted((root / "deployment").glob("*.md")) + sorted((root / "governance").glob("*.md")):
        referenced.update(re.findall(r"\bADR-\d{4}\b", path.read_text(encoding="utf-8", errors="ignore")))
    for adr in sorted(referenced - existing):
        findings.append(
            _finding(
                "major",
                "Missing ADRs",
                f"wiki/decisions/{adr}",
                f"{adr} is referenced but no matching ADR file exists.",
                "Create the ADR or remove the stale reference.",
                "Solution Architect",
            )
        )
    if not existing:
        findings.append(
            _finding(
                "critical",
                "Missing ADRs",
                "wiki/decisions",
                "No ADR records exist for architecture governance.",
                "Create ADR records for accepted architecture decisions.",
                "Solution Architect",
            )
        )
    return findings


def _missing_tests(root: Path) -> list[IntegrityFinding]:
    findings = []
    validation_text = _read_all(root / "validation")
    for req in sorted(_ids(root / "requirements", r"\bREQ-\d+\b")):
        if req not in validation_text:
            findings.append(
                _finding(
                    "major",
                    "Missing tests",
                    f"wiki/requirements/{req}",
                    f"{req} is not referenced by validation artifacts.",
                    "Add validation coverage or record a scoped deferral.",
                    "QA Agent",
                )
            )
    return findings[:60]


def _missing_evidence(repo_root: Path, cfg: ProjectConfig, root: Path) -> list[IntegrityFinding]:
    findings = []
    registry = ensure_registry(repo_root / cfg.evidence_registry)
    artifacts = registry.get("artifacts", {}) if isinstance(registry, dict) else {}
    evidence_text = _read_all(root / "validation") + "\n" + _read_all(root / "deployment") + "\n" + _read_all(root / "work")
    referenced = set(re.findall(r"\bEVID-[A-Z0-9\-]{3,}\b", evidence_text))
    for evid in sorted(referenced):
        if evid not in artifacts:
            findings.append(
                _finding(
                    "major",
                    "Missing evidence",
                    evid,
                    f"{evid} is referenced but not registered in the evidence registry.",
                    "Register the evidence or mark it as a planned target outside release scope.",
                    "QA Agent",
                )
            )
    if "release" in evidence_text.lower() and not artifacts:
        findings.append(
            _finding(
                "critical",
                "Missing evidence",
                ".echel/evidence_registry.json",
                "Release-related product memory exists but the evidence registry is empty.",
                "Register validation or release evidence before production claims.",
                "Release Manager",
            )
        )
    return findings[:80]


def _methodology_violations(root: Path) -> list[IntegrityFinding]:
    findings = []
    work_dir = root / "work"
    for path in sorted(work_dir.glob("TASK-*.md")):
        text = path.read_text(encoding="utf-8", errors="ignore")
        if "status: done" in text and "EVID-" not in text:
            findings.append(
                _finding(
                    "major",
                    "Methodology violations",
                    _rel(root, path),
                    "Done task does not reference registered evidence.",
                    "Add evidence reference, reopen task, or record an accepted exception.",
                    "Governance Auditor",
                )
            )
    return findings[:80]


def _open_contradictions(root: Path) -> list[IntegrityFinding]:
    path = root / "governance" / "contradictions.md"
    findings = []
    if not path.exists():
        return findings
    for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        stripped = line.strip()
        if not stripped.startswith("| CONTR-") or "---" in stripped or "CONTR-000" in stripped:
            continue
        cells = [cell.strip().strip("`") for cell in stripped.strip("|").split("|")]
        if len(cells) < 8:
            continue
        status = cells[1].lower()
        if status in {"resolved", "accepted"}:
            continue
        findings.append(
            _finding(
                "major",
                "Contradictions",
                "wiki/governance/contradictions.md",
                f"{cells[0]} remains {cells[1]}: {cells[2]}",
                f"Complete {cells[7]} or record an accepted exception.",
                "Governance Auditor",
            )
        )
    return findings[:40]


def _finding(severity: str, area: str, source: str, impact: str, action: str, owner: str) -> IntegrityFinding:
    return IntegrityFinding("", severity, area, source, impact, action, owner)


def _read_all(path: Path) -> str:
    if path.is_file():
        return path.read_text(encoding="utf-8", errors="ignore")
    if not path.exists():
        return ""
    return "\n".join(item.read_text(encoding="utf-8", errors="ignore") for item in sorted(path.glob("**/*.md")))


def _ids(path: Path, pattern: str) -> set[str]:
    return set(re.findall(pattern, _read_all(path)))


def _rel(root: Path, path: Path) -> str:
    try:
        return f"wiki/{path.relative_to(root).as_posix()}"
    except ValueError:
        return path.as_posix()


def _escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def _append_log(root: Path, line: str) -> None:
    log = root / "log.md"
    if not log.exists():
        return
    text = log.read_text(encoding="utf-8")
    entry = f"\n## [2026-07-13] governance | integrity-audit\n- {line}\n"
    if line not in text:
        log.write_text(text.rstrip() + entry, encoding="utf-8")
