from __future__ import annotations

from collections import defaultdict, deque
from dataclasses import dataclass
from pathlib import Path

from .config import ProjectConfig
from .graph import build_graph, validate_graph, wiki_root


REPORT_PATH = "reports/traceability-matrix.md"


@dataclass(frozen=True)
class Stage:
    key: str
    title: str
    node_types: frozenset[str]


STAGES = (
    Stage("discovery", "Discovery", frozenset({"discovery-item", "assumption", "hypothesis", "buyer", "stakeholder", "risk", "problem", "user", "need", "workflow"})),
    Stage("canon", "Canon", frozenset({"canon"})),
    Stage("strategy", "Strategy", frozenset({"strategy"})),
    Stage("requirement", "Requirement", frozenset({"requirement"})),
    Stage("domain", "Domain", frozenset({"domain-concept", "bounded-context", "business-rule", "domain-aggregate", "domain-event", "domain-workflow"})),
    Stage("architecture", "Architecture", frozenset({"architecture", "architecture-component", "decision", "component"})),
    Stage("task", "Task", frozenset({"task"})),
    Stage("test", "Test", frozenset({"test"})),
    Stage("evidence", "Evidence", frozenset({"evidence"})),
)


@dataclass(frozen=True)
class Artifact:
    id: str
    label: str
    title: str
    source: str
    stage: str
    graph_node: bool


def write_traceability_matrix(repo_root: Path, cfg: ProjectConfig) -> Path:
    root = wiki_root(repo_root, cfg)
    graph = build_graph(repo_root, cfg)
    report = traceability_matrix_report(repo_root, cfg, graph=graph)
    path = root / REPORT_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(report.rstrip() + "\n", encoding="utf-8")
    return path


def traceability_matrix_report(repo_root: Path, cfg: ProjectConfig, graph: dict | None = None) -> str:
    root = wiki_root(repo_root, cfg)
    graph = graph or build_graph(repo_root, cfg)
    graph_nodes = [node for node in graph.get("nodes", []) if isinstance(node, dict)]
    graph_edges = [edge for edge in graph.get("edges", []) if isinstance(edge, dict)]
    artifacts = _artifacts_by_stage(root, graph_nodes)
    adjacency = _undirected_adjacency(graph_edges)
    anchors = sorted(artifacts["requirement"], key=lambda a: _sort_key(a.label))
    if not anchors:
        anchors = sorted((artifact for group in artifacts.values() for artifact in group if artifact.graph_node), key=lambda a: _sort_key(a.label))

    rows = []
    linked_by_stage: dict[str, set[str]] = {stage.key: set() for stage in STAGES}
    for anchor in anchors:
        reachable = _reachable(anchor.id, adjacency)
        reachable.add(anchor.id)
        row_cells: dict[str, list[Artifact]] = {}
        missing: list[str] = []
        for stage in STAGES:
            stage_artifacts = [
                artifact
                for artifact in artifacts[stage.key]
                if artifact.graph_node and artifact.id in reachable
            ]
            if stage.key == "requirement" and not stage_artifacts:
                stage_artifacts = [anchor]
            if stage_artifacts:
                linked_by_stage[stage.key].update(artifact.id for artifact in stage_artifacts)
            else:
                missing.append(stage.title)
            row_cells[stage.key] = sorted(stage_artifacts, key=lambda a: _sort_key(a.label))
        rows.append((anchor, row_cells, missing))

    broken_rows = [(anchor, missing) for anchor, _cells, missing in rows if missing]
    complete_rows = len(rows) - len(broken_rows)
    graph_issues = validate_graph(graph)

    lines: list[str] = [
        "---",
        "type: traceability-report",
        "status: active",
        "stage: governance",
        "---",
        "# Traceability Matrix",
        "",
        "Generated by `python3 tools/echel.py traceability` from the product graph and canonical wiki artifacts.",
        "",
        "## Lifecycle Chain",
        "",
        "`discovery -> canon -> strategy -> requirement -> domain -> architecture -> task -> test -> evidence`",
        "",
        "## Summary",
        "",
        f"- Matrix anchor rows: {len(rows)}",
        f"- Complete chains: {complete_rows}",
        f"- Broken chains: {len(broken_rows)}",
        f"- Graph nodes analyzed: {len(graph_nodes)}",
        f"- Graph edges analyzed: {len(graph_edges)}",
        "",
        "## Stage Coverage",
        "",
        "| Stage | Total Artifacts | Linked In Matrix | Coverage |",
        "| --- | ---: | ---: | ---: |",
    ]
    for stage in STAGES:
        total = len(artifacts[stage.key])
        linked = len(linked_by_stage[stage.key])
        coverage = _percent(linked, total)
        lines.append(f"| {stage.title} | {total} | {linked} | {coverage} |")

    lines.extend(
        [
            "",
            "## Lifecycle Matrix",
            "",
            "| Anchor | Discovery | Canon | Strategy | Requirement | Domain | Architecture | Task | Test | Evidence | Broken Links |",
            "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    for anchor, cells, missing in rows:
        cell_text = [_format_artifacts(cells[stage.key]) for stage in STAGES]
        broken = "None" if not missing else "Missing: " + ", ".join(missing)
        lines.append(f"| {_escape(anchor.label)} | " + " | ".join(cell_text) + f" | {_escape(broken)} |")

    lines.extend(
        [
            "",
            "## Broken Chains",
            "",
        ]
    )
    if broken_rows:
        for anchor, missing in broken_rows:
            lines.append(f"- `{anchor.label}` is missing {', '.join(missing)} links.")
    else:
        lines.append("- No broken lifecycle chains detected.")

    lines.extend(
        [
            "",
            "## Artifact Families",
            "",
            "| Stage | Artifact IDs |",
            "| --- | --- |",
        ]
    )
    for stage in STAGES:
        lines.append(f"| {stage.title} | {_format_artifacts(artifacts[stage.key], limit=12)} |")

    lines.extend(
        [
            "",
            "## Graph Integrity",
            "",
        ]
    )
    if graph_issues:
        for issue in graph_issues:
            lines.append(f"- {issue.severity}: {issue.message}")
    else:
        lines.append("- Product graph validation has no reported issues.")

    lines.extend(
        [
            "",
            "## Notes",
            "",
            "- Matrix rows are requirement-centered because requirements are the methodology handoff between product intent and delivery work.",
            "- Graph relationships are traversed as lifecycle associations so the report can expose broken coverage even when edge direction differs by artifact family.",
            "- Canon artifacts are counted from `wiki/canon/*.md`; they remain broken until the graph contains explicit canon statement nodes or downstream canon references.",
        ]
    )
    return "\n".join(lines)


def _artifacts_by_stage(root: Path, graph_nodes: list[dict]) -> dict[str, list[Artifact]]:
    artifacts: dict[str, list[Artifact]] = {stage.key: [] for stage in STAGES}
    stage_by_type = {node_type: stage.key for stage in STAGES for node_type in stage.node_types}
    for node in graph_nodes:
        node_id = str(node.get("id") or "")
        node_type = str(node.get("type") or "")
        source_stage = str(node.get("source_stage") or "")
        stage_key = stage_by_type.get(node_type)
        if not stage_key and source_stage in artifacts:
            stage_key = source_stage
        if not stage_key:
            continue
        artifacts[stage_key].append(
            Artifact(
                id=node_id,
                label=str(node.get("trace_id") or node_id),
                title=str(node.get("title") or node_id),
                source=str(node.get("source") or ""),
                stage=stage_key,
                graph_node=True,
            )
        )

    canon_root = root / "canon"
    for path in sorted(canon_root.glob("*.md")):
        stem = path.stem
        artifacts["canon"].append(
            Artifact(
                id=f"canon:{stem}",
                label=f"CANON:{stem}",
                title=_title(path) or stem.replace("-", " ").title(),
                source=str(path.relative_to(root)),
                stage="canon",
                graph_node=False,
            )
        )

    for stage_key, values in artifacts.items():
        unique: dict[str, Artifact] = {}
        for artifact in values:
            unique[artifact.id] = artifact
        artifacts[stage_key] = sorted(unique.values(), key=lambda a: _sort_key(a.label))
    return artifacts


def _undirected_adjacency(edges: list[dict]) -> dict[str, set[str]]:
    adjacency: dict[str, set[str]] = defaultdict(set)
    for edge in edges:
        source = str(edge.get("from_id") or "")
        target = str(edge.get("to_id") or "")
        if source and target:
            adjacency[source].add(target)
            adjacency[target].add(source)
    return adjacency


def _reachable(start: str, adjacency: dict[str, set[str]]) -> set[str]:
    seen: set[str] = set()
    queue: deque[str] = deque([start])
    while queue:
        current = queue.popleft()
        if current in seen:
            continue
        seen.add(current)
        for nxt in sorted(adjacency.get(current, set())):
            if nxt not in seen:
                queue.append(nxt)
    return seen


def _format_artifacts(artifacts: list[Artifact], limit: int = 6) -> str:
    if not artifacts:
        return "Missing"
    labels = [f"`{_escape(artifact.label)}`" for artifact in artifacts[:limit]]
    if len(artifacts) > limit:
        labels.append(f"+{len(artifacts) - limit} more")
    return "<br>".join(labels)


def _percent(part: int, total: int) -> str:
    if total == 0:
        return "0%"
    return f"{round((part / total) * 100)}%"


def _sort_key(value: str) -> tuple[str, int, str]:
    prefix = "".join(ch for ch in value if not ch.isdigit())
    digits = "".join(ch for ch in value if ch.isdigit())
    return (prefix, int(digits or 0), value)


def _title(path: Path) -> str:
    if not path.exists():
        return ""
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return ""


def _escape(value: str) -> str:
    return value.replace("|", "\\|")
